---
- name: Cleanup networks
  os_network:
      cloud: "{{ provision.cloud | default(omit) }}"
      name: "{{ item.id }}"
      state: absent
  with_items: "{{ lookup('file', inventory_dir + '/resources/networks.yml') | from_yaml }}"
  register: networks_cleanup
