---
# This file is used to cleanup OpenStack neutron resources
- stat:
      path: "{{ inventory_dir }}/resources/routers.yml"
  register: routers_file

- include: "tasks/cleanup/routers.yml"
  when: routers_file.stat.exists
  register: routers_out

- stat:
      path: "{{ inventory_dir }}/resources/subnets.yml"
  register: subnets_file

- include: "tasks/cleanup/subnets.yml"
  when: subnets_file.stat.exists

- stat:
      path: "{{ inventory_dir }}/resources/networks.yml"
  register: networks_file

- include: "tasks/cleanup/networks.yml"
  when: networks_file.stat.exists

#TODO(aopincar): Add 'security groups' cleanup task

- name: Fail run if one of neutron cleanups tasks failed/skipped
  fail: msg="The run failed because one of neutron cleanup tasks failed/skipped"
  when: (routers_cleanup|skipped or subnets_cleanup|skipped or networks_cleanup|skipped)


